export { vlColorStyles } from './base/style/vl-color.css';
export { globalStylesNext, RegisterGlobalStyles } from './global-styles-decorator';
export { iconFontLocation } from './base/font/vl-font.css';
export { vlIconStyles } from './icon/vl-icon.css';
export { vlLinkStyles } from './link/vl-link.css';
export { vlFocusOutlineMixin } from './base/mixin/vl-outlines.css';
export { vlWaveAnimationMixin } from './base/mixin/vl-animations.css';
export { vlHeadingMixin } from './base/mixin/vl-headings.css';
export { vlGridStyles } from './grid/vl-grid.css';
export { vlGroupStyles } from './group/vl-group.css';
export { vlMarginStyles } from './space/vl-margin.css';
export { vlPaddingStyles } from './space/vl-padding.css';
